"""
Pentest Pipeline Markdown Report parser.

Parses the aggregated report.md generated by pentest-workbench (07_report.sh)
and produces NormalizedVulnerability objects that populate the attack_surface
report sections in Shelter.

Category mapping used by the template macros:
  "Passive Recon"     → mac_passive_recon()
  "Network Exposure"  → mac_network_overview()
  "Security Headers"  → mac_web_surface()
  "Web Surface"       → mac_web_surface()
  "Content Discovery" → mac_content_discovery()
  "CWE-79"            → vuln_details (XSS)
  "Default Credentials" → vuln_details
  ""                  → vuln_details (generic nuclei findings)
"""

from __future__ import annotations

import logging
import re
from typing import IO

from apps.vulnerabilities.deduplication import NormalizedVulnerability

from .base import BaseParser, ParserError

logger = logging.getLogger(__name__)


def _code_blocks(text: str) -> list[str]:
    return re.findall(r"```[^\n]*\n(.*?)```", text, re.DOTALL)


def _first_code_block(text: str) -> str:
    blocks = _code_blocks(text)
    return blocks[0].strip() if blocks else ""


def _host_from_url(url: str, fallback: str = "") -> str:
    m = re.match(r"https?://([^/:?\s]+)", url)
    return m.group(1) if m else fallback


def _port_from_url(url: str) -> int | None:
    if re.match(r"https?://[^/:]+:\d+", url):
        m = re.search(r":(\d+)", url.split("//", 1)[-1])
        return int(m.group(1)) if m else None
    if url.startswith("https://"):
        return 443
    if url.startswith("http://"):
        return 80
    return None


class PipelineMdParser(BaseParser):
    """Parser for pentest-workbench pipeline report.md output (07_report.sh)."""

    tool_name = "pentest_pipeline"

    def parse(self, file_obj: IO[bytes]) -> list[NormalizedVulnerability]:
        raw = file_obj.read()
        try:
            text = raw.decode("utf-8", errors="replace")
        except Exception as exc:
            raise ParserError(f"Cannot decode pipeline report: {exc}") from exc

        if not text.strip():
            logger.info("[pentest_pipeline] Empty file — 0 findings.")
            return []

        sections = self._split_h1(text)

        # Extract target from the header section
        header = sections.get("security assessment report", "")
        target_m = re.search(r"\*\*Target:\*\*\s*`([^`]+)`", header)
        target = target_m.group(1) if target_m else ""

        results: list[NormalizedVulnerability] = []

        if "passive osint" in sections:
            results.extend(self._parse_passive_osint(sections["passive osint"], target))

        if "network reconnaissance" in sections:
            results.extend(self._parse_network(sections["network reconnaissance"], target))

        if "web surface" in sections:
            results.extend(self._parse_web_surface(sections["web surface"], target))

        if "content discovery" in sections:
            results.extend(self._parse_content_discovery(sections["content discovery"], target))

        if "vulnerabilities" in sections:
            results.extend(self._parse_vulnerabilities(sections["vulnerabilities"], target))

        logger.info("[pentest_pipeline] Extracted %d findings for target '%s'.", len(results), target)
        return results

    # ── Section parsers ──────────────────────────────────────────────────────

    def _parse_passive_osint(self, body: str, target: str) -> list[NormalizedVulnerability]:
        results: list[NormalizedVulnerability] = []
        h2s = self._split_h2(body)

        subdomains: list[str] = []
        subdomain_body = next((v for k, v in h2s.items() if "passive subdomains" in k), "")
        if subdomain_body:
            block = _first_code_block(subdomain_body)
            subdomains = [ln.strip() for ln in block.splitlines() if ln.strip()]

        dns_data = _first_code_block(h2s.get("dns records", ""))
        asn_data = _first_code_block(h2s.get("ip & asn", ""))
        shodan_data = _first_code_block(h2s.get("shodan", ""))

        desc_parts: list[str] = []
        if subdomains:
            preview = ", ".join(subdomains[:20])
            suffix = f" … and {len(subdomains) - 20} more" if len(subdomains) > 20 else ""
            desc_parts.append(f"Subdomains discovered ({len(subdomains)}): {preview}{suffix}")
        if dns_data:
            desc_parts.append(f"DNS records:\n{dns_data[:500]}")
        if asn_data:
            desc_parts.append(f"ASN/IP info:\n{asn_data[:300]}")
        if shodan_data:
            desc_parts.append(f"Shodan:\n{shodan_data[:500]}")

        if desc_parts or subdomains:
            results.append(NormalizedVulnerability(
                title=f"Passive Recon Summary — {target}",
                description="\n\n".join(desc_parts) or f"Passive OSINT conducted for {target}.",
                affected_host=target,
                risk_level="info",
                category="Passive Recon",
                source="pentest_pipeline",
                evidence_code="\n".join(subdomains[:100])[:4096],
            ))

        # One info finding per subdomain for host_breakdown visibility
        # Capped at 50 to avoid flooding the report
        for sub in subdomains[:50]:
            results.append(NormalizedVulnerability(
                title=f"Discovered Subdomain: {sub}",
                description="Subdomain identified via passive reconnaissance (CT logs, DNS, OSINT sources).",
                affected_host=sub,
                risk_level="info",
                category="Passive Recon",
                source="pentest_pipeline",
            ))

        return results

    def _parse_network(self, body: str, target: str) -> list[NormalizedVulnerability]:
        results: list[NormalizedVulnerability] = []
        h2s = self._split_h2(body)

        tcp_block = _first_code_block(h2s.get("open services", ""))
        if tcp_block:
            port_lines = [ln for ln in tcp_block.splitlines() if re.search(r"^\d+/tcp\s+open", ln)]
            if port_lines:
                results.append(NormalizedVulnerability(
                    title=f"Open TCP Services — {target}",
                    description="TCP services found open on the target during port scan:\n\n" + "\n".join(port_lines),
                    affected_host=target,
                    risk_level="info",
                    category="Network Exposure",
                    source="pentest_pipeline",
                    evidence_code=tcp_block[:4096],
                ))

        udp_block = _first_code_block(h2s.get("udp services", ""))
        if udp_block:
            udp_lines = [ln for ln in udp_block.splitlines() if re.search(r"^\d+/udp\s+open", ln)]
            if udp_lines:
                results.append(NormalizedVulnerability(
                    title=f"Open UDP Services — {target}",
                    description="UDP services found open on the target:\n\n" + "\n".join(udp_lines),
                    affected_host=target,
                    risk_level="info",
                    category="Network Exposure",
                    source="pentest_pipeline",
                    evidence_code=udp_block[:4096],
                ))

        nse_body = h2s.get("nse notable findings", "")
        if nse_body:
            # Split on **service:** markers
            chunks = re.split(r"\*\*([^*]+):\*\*", nse_body)
            for i in range(1, len(chunks), 2):
                service = chunks[i].strip()
                content_area = chunks[i + 1] if i + 1 < len(chunks) else ""
                blocks = _code_blocks(content_area)
                if not blocks:
                    continue
                content = blocks[0].strip()
                if not content:
                    continue
                risk = "medium" if re.search(r"VULNERABLE|CRITICAL", content, re.IGNORECASE) else "low"
                results.append(NormalizedVulnerability(
                    title=f"NSE Finding: {service} — {target}",
                    description=f"Nmap NSE script identified notable finding on {service} service.",
                    remediation=f"Review and harden the {service} service configuration.",
                    affected_host=target,
                    affected_service=service,
                    risk_level=risk,
                    category="Network Exposure",
                    source="pentest_pipeline",
                    evidence_code=content[:4096],
                ))

        return results

    def _parse_web_surface(self, body: str, target: str) -> list[NormalizedVulnerability]:
        results: list[NormalizedVulnerability] = []
        h2s = self._split_h2(body)

        # Missing security headers — group by host
        headers_body = h2s.get("security headers", "")
        if headers_body:
            block = _first_code_block(headers_body)
            missing_lines = [ln.strip() for ln in block.splitlines() if "[MISSING]" in ln]
            host_missing: dict[str, list[str]] = {}
            for line in missing_lines:
                m = re.match(r"\[MISSING\]\s+(https?://[^\s]+)\s+(.+)", line)
                if m:
                    host_missing.setdefault(m.group(1), []).append(m.group(2).strip())
            for host_url, missing_headers in host_missing.items():
                host = _host_from_url(host_url, target)
                port = _port_from_url(host_url)
                results.append(NormalizedVulnerability(
                    title=f"Missing Security Headers — {host}",
                    description=(
                        f"The following security headers are absent from {host_url}:\n\n"
                        + "\n".join(f"- {h}" for h in missing_headers)
                    ),
                    remediation=(
                        "Configure the web server to include the missing headers. "
                        "Priority: Content-Security-Policy, Strict-Transport-Security, "
                        "X-Frame-Options, X-Content-Type-Options, Referrer-Policy."
                    ),
                    affected_host=host,
                    affected_port=port,
                    affected_service="HTTPS" if port == 443 else "HTTP",
                    risk_level="low",
                    category="Security Headers",
                    source="pentest_pipeline",
                    evidence_code="\n".join(missing_lines)[:4096],
                ))

        # WAF Detection
        waf_body = h2s.get("waf detection", "")
        if waf_body:
            block = _first_code_block(waf_body)
            if block.strip():
                results.append(NormalizedVulnerability(
                    title=f"WAF Detected — {target}",
                    description=f"A Web Application Firewall was detected during the assessment.\n\n{block.strip()[:600]}",
                    affected_host=target,
                    risk_level="info",
                    category="Web Surface",
                    source="pentest_pipeline",
                    evidence_code=block[:4096],
                ))

        # Technology stack fingerprint
        tech_body = h2s.get("technology stack", "")
        if tech_body:
            block = _first_code_block(tech_body)
            if block.strip():
                results.append(NormalizedVulnerability(
                    title=f"Technology Stack Fingerprint — {target}",
                    description=f"Technology fingerprinting identified the following components:\n\n{block.strip()[:800]}",
                    affected_host=target,
                    risk_level="info",
                    category="Web Surface",
                    source="pentest_pipeline",
                    evidence_code=block[:4096],
                ))

        return results

    def _parse_content_discovery(self, body: str, target: str) -> list[NormalizedVulnerability]:
        results: list[NormalizedVulnerability] = []
        h2s = self._split_h2(body)

        # Discovered paths — group by host, flag sensitive
        paths_body = next((v for k, v in h2s.items() if "discovered paths" in k), "")
        if paths_body:
            block = _first_code_block(paths_body)
            paths = [ln.strip() for ln in block.splitlines() if ln.strip()]
            host_paths: dict[str, list[str]] = {}
            for path in paths:
                h = _host_from_url(path, target)
                host_paths.setdefault(h, []).append(path)
            for host, hpaths in host_paths.items():
                sensitive = [p for p in hpaths if re.search(
                    r"admin|backup|\.sql|\.bak|\.env|\.git|config|debug|phpinfo|console",
                    p, re.IGNORECASE,
                )]
                risk = "medium" if sensitive else "low"
                desc = f"Content discovery identified {len(hpaths)} interesting path(s) on {host}."
                if sensitive:
                    desc += "\n\nSensitive paths requiring review:\n" + "\n".join(sensitive)
                results.append(NormalizedVulnerability(
                    title=f"Sensitive Paths Discovered — {host}",
                    description=desc,
                    remediation=(
                        "Restrict access to administrative interfaces, configuration files, and backup artifacts. "
                        "Ensure .git directories and backup files are not accessible from the web root."
                    ),
                    affected_host=host,
                    risk_level=risk,
                    category="Content Discovery",
                    source="pentest_pipeline",
                    evidence_code="\n".join(hpaths)[:4096],
                ))

        # API endpoints
        api_body = h2s.get("api endpoints", "")
        if api_body:
            block = _first_code_block(api_body)
            if block.strip():
                endpoints = [ln.strip() for ln in block.splitlines() if ln.strip()]
                host_eps: dict[str, list[str]] = {}
                for ep in endpoints:
                    h = _host_from_url(ep, target)
                    host_eps.setdefault(h, []).append(ep)
                for host, eps in host_eps.items():
                    results.append(NormalizedVulnerability(
                        title=f"API Endpoints Discovered — {host}",
                        description=(
                            f"The following API endpoints were identified during content discovery on {host}:\n\n"
                            + "\n".join(eps[:50])
                        ),
                        affected_host=host,
                        risk_level="info",
                        category="Content Discovery",
                        source="pentest_pipeline",
                        evidence_code="\n".join(eps)[:4096],
                    ))

        # Potential secrets in JavaScript
        secrets_body = h2s.get("potential secrets in javascript", "")
        if secrets_body:
            block = _first_code_block(secrets_body)
            if block.strip():
                results.append(NormalizedVulnerability(
                    title=f"Potential Secrets in JavaScript — {target}",
                    description=(
                        "Hardcoded secrets or sensitive configuration values were detected in publicly "
                        "accessible JavaScript files. Manual review is required to confirm findings.\n\n"
                        + block.strip()[:600]
                    ),
                    remediation=(
                        "Remove all secrets from client-side JavaScript. "
                        "Use server-side endpoints for sensitive operations. "
                        "Rotate any confirmed exposed credentials immediately."
                    ),
                    affected_host=target,
                    risk_level="medium",
                    category="Content Discovery",
                    source="pentest_pipeline",
                    evidence_code=block[:4096],
                ))

        return results

    def _parse_vulnerabilities(self, body: str, target: str) -> list[NormalizedVulnerability]:
        results: list[NormalizedVulnerability] = []
        h2s = self._split_h2(body)

        # Critical & High nuclei findings
        crit_body = next((v for k, v in h2s.items() if "critical" in k and "high" in k), "")
        if crit_body:
            block = _first_code_block(crit_body)
            results.extend(self._parse_nuclei_text(block, target))

        # Medium nuclei findings
        medium_body = next((v for k, v in h2s.items() if k.startswith("medium severity")), "")
        if medium_body:
            block = _first_code_block(medium_body)
            results.extend(self._parse_nuclei_text(block, target))

        # XSS findings (dalfox)
        xss_body = next((v for k, v in h2s.items() if "xss" in k), "")
        if xss_body:
            block = _first_code_block(xss_body)
            for line in block.splitlines():
                if "[V]" not in line:
                    continue
                url_m = re.search(r"https?://\S+", line)
                url = url_m.group(0) if url_m else ""
                host = _host_from_url(url, target)
                port = _port_from_url(url)
                results.append(NormalizedVulnerability(
                    title="Cross-Site Scripting (XSS)",
                    description=f"Reflected XSS confirmed by dalfox.\nPayload URL: {url}",
                    remediation=(
                        "Implement output encoding for all user-supplied input rendered in HTML context. "
                        "Review and tighten the Content-Security-Policy header."
                    ),
                    affected_host=host,
                    affected_port=port,
                    risk_level="high",
                    category="CWE-79",
                    source="pentest_pipeline",
                    evidence_code=line[:4096],
                ))

        # Default credentials
        creds_body = h2s.get("default credentials", "")
        if creds_body:
            block = _first_code_block(creds_body)
            for line in block.splitlines():
                if "[CREDS]" not in line:
                    continue
                url_m = re.search(r"https?://\S+", line)
                url = url_m.group(0) if url_m else ""
                host = _host_from_url(url, target)
                name_m = re.search(r"\[CREDS\]\s+(.+?)\s+—", line)
                name = name_m.group(1).strip() if name_m else "Default Credentials"
                results.append(NormalizedVulnerability(
                    title=f"Default Credentials — {name}",
                    description=f"Default credentials were confirmed valid for the service at {url or host}.",
                    remediation=(
                        "Change default credentials immediately. "
                        "Enforce a strong password policy and enable multi-factor authentication."
                    ),
                    affected_host=host,
                    risk_level="critical",
                    category="Default Credentials",
                    source="pentest_pipeline",
                    evidence_code=line[:4096],
                ))

        return results

    def _parse_nuclei_text(self, block: str, default_host: str) -> list[NormalizedVulnerability]:
        """
        Parse nuclei findings as formatted by 07_report.sh:
          [SEVERITY] Title
            URL: https://...
            CVE: CVE-XXXX or n/a
            Tags: tag1,tag2
        """
        results: list[NormalizedVulnerability] = []
        # Split on severity markers
        finding_blocks = re.split(r"\n(?=\[(?:CRITICAL|HIGH|MEDIUM|LOW|INFO)\])", "\n" + block.strip())
        for fb in finding_blocks:
            fb = fb.strip()
            if not fb:
                continue
            sev_m = re.match(r"\[(CRITICAL|HIGH|MEDIUM|LOW|INFO)\]\s+(.+)", fb, re.IGNORECASE)
            if not sev_m:
                continue
            severity = sev_m.group(1).lower()
            title = sev_m.group(2).strip()

            url_m = re.search(r"URL:\s*(https?://\S+)", fb)
            url = url_m.group(1) if url_m else ""
            host = _host_from_url(url, default_host)
            port = _port_from_url(url)

            cve_m = re.search(r"CVE:\s*(.+)", fb)
            cve_raw = cve_m.group(1).strip() if cve_m else ""
            cve_list = [c.strip() for c in cve_raw.split(",") if c.strip().lower() not in ("", "n/a")]

            tags_m = re.search(r"Tags:\s*(.+)", fb)
            tags = tags_m.group(1).strip() if tags_m else ""

            category = ""
            if "xss" in tags.lower():
                category = "CWE-79"
            elif "sqli" in tags.lower() or "sql" in tags.lower():
                category = "CWE-89"

            results.append(NormalizedVulnerability(
                title=title,
                description=f"Detected by nuclei.{chr(10)}Tags: {tags}" if tags else "Detected by nuclei.",
                affected_host=host,
                affected_port=port,
                cve_id=cve_list,
                risk_level=severity,
                category=category,
                source="pentest_pipeline",
                evidence_code=fb[:4096],
            ))

        return results

    # ── Helpers ──────────────────────────────────────────────────────────────

    @staticmethod
    def _split_h1(text: str) -> dict[str, str]:
        parts = re.split(r"\n# ", "\n" + text)
        result: dict[str, str] = {}
        for part in parts:
            if not part.strip():
                continue
            lines = part.split("\n", 1)
            title = lines[0].strip().lower()
            content = lines[1] if len(lines) > 1 else ""
            result[title] = content
        return result

    @staticmethod
    def _split_h2(body: str) -> dict[str, str]:
        parts = re.split(r"\n+## ", "\n" + body)
        result: dict[str, str] = {}
        for part in parts:
            if not part.strip():
                continue
            lines = part.split("\n", 1)
            title = lines[0].strip().lower()
            content = lines[1] if len(lines) > 1 else ""
            result[title] = content
        return result
