# Generated by Django 5.0.4 on 2026-03-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial_active', 'Trial Active'), ('trial_expired', 'Trial Expired'), ('pro_active', 'PRO Active'), ('pro_expired', 'PRO Expired'), ('invalid', 'Invalid')], default='trial_active', max_length=32)),
                ('license_key', models.CharField(blank=True, default='', max_length=255)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pro_activated_at', models.DateTimeField(blank=True, null=True)),
                ('pro_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
