# Generated by Django 5.1.15 on 2026-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0003_license_activation_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="activation_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
