# Generated by Django 5.0.4 on 2026-03-03 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='projects/client_logos/')),
                ('client_contact', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=64)),
                ('primary_color', models.CharField(default='#3b82f6', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', max_length=7)),
                ('font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Source Sans Pro', 'Source Sans Pro'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato')], default='Inter', max_length=64)),
                ('watermark_text', models.CharField(blank=True, max_length=128)),
                ('watermark_image', models.ImageField(blank=True, null=True, upload_to='projects/watermarks/')),
                ('watermark_opacity', models.FloatField(default=0.15)),
                ('header_logo_left', models.BooleanField(default=True)),
                ('header_text_center', models.CharField(blank=True, max_length=255)),
                ('header_show_date', models.BooleanField(default=True)),
                ('footer_text', models.TextField(blank=True)),
                ('footer_page_numbering', models.CharField(choices=[('n_of_total', 'N / TOT'), ('n_only', 'N'), ('none', 'None')], default='n_of_total', max_length=16)),
                ('template_name', models.CharField(default='default', max_length=64)),
                ('template_html', models.FileField(blank=True, null=True, upload_to='projects/templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_locks', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Lock',
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Membership',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='accessible_projects', through='projects.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subprojects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='projects.project')),
            ],
            options={
                'verbose_name': 'SubProject',
                'verbose_name_plural': 'SubProjects',
                'ordering': ['scan_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_ref', models.PositiveIntegerField(blank=True, help_text='FK to Vulnerability.id', null=True)),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=512)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_screenshots', to=settings.AUTH_USER_MODEL)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='projects.subproject')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
