# Generated by Django 5.0.4 on 2026-03-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('nmap', 'Nmap'), ('nikto', 'Nikto'), ('burp', 'Burp Suite'), ('zap', 'OWASP ZAP'), ('metasploit', 'Metasploit'), ('csv', 'Generic CSV'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('file', models.FileField(upload_to='imports/quarantine/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('vulnerability_count', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_imports', to=settings.AUTH_USER_MODEL)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_imports', to='projects.subproject')),
            ],
            options={
                'verbose_name': 'Scan Import',
                'verbose_name_plural': 'Scan Imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('affected_host', models.CharField(blank=True, max_length=255)),
                ('affected_port', models.CharField(blank=True, max_length=16)),
                ('affected_service', models.CharField(blank=True, max_length=128)),
                ('cve_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=255)),
                ('epss_score', models.FloatField(blank=True, help_text='Exploit Prediction Scoring System (0-1)', null=True)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='medium', max_length=16)),
                ('risk_score', models.FloatField(blank=True, help_text='Composite score: f(cvss, epss, exposure_factor)', null=True)),
                ('vuln_status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('accepted', 'Risk Accepted'), ('retest', 'Needs Retest')], default='open', max_length=16)),
                ('sources', models.JSONField(default=list, help_text='Tools that identified this vulnerability (after dedup)')),
                ('raw_outputs', models.JSONField(default=list, help_text='List of raw tool outputs (before normalization)')),
                ('is_recurring', models.BooleanField(default=False, help_text='True if this vulnerability was also present in the previous SubProject')),
                ('evidence_code', models.TextField(blank=True, help_text='Raw output / code snippet as evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='vulnerabilities.scanimport')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='projects.subproject')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-risk_score', '-cvss_score', 'title'],
                'indexes': [models.Index(fields=['subproject', 'title', 'affected_host', 'affected_port'], name='vulnerabili_subproj_b1167f_idx'), models.Index(fields=['vuln_status'], name='vulnerabili_vuln_st_7f1dd9_idx'), models.Index(fields=['risk_level'], name='vulnerabili_risk_le_a21c6a_idx')],
            },
        ),
    ]
