# Generated by Django 6.0.4 on 2026-05-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0010_alter_scanimport_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanimport",
            name="tool",
            field=models.CharField(
                choices=[
                    ("nmap", "Nmap"),
                    ("nikto", "Nikto"),
                    ("burp", "Burp Suite"),
                    ("zap", "OWASP ZAP"),
                    ("metasploit", "Metasploit"),
                    ("csv", "Generic CSV"),
                    ("openvas", "OpenVAS / Greenbone"),
                    ("nessus", "Nessus"),
                    ("acunetix", "Acunetix / Acunetix 360"),
                    ("arachni", "Arachni"),
                    ("aws_inspector2", "AWS Inspector v2"),
                    ("awssecurityhub", "AWS Security Hub"),
                    ("cargo_audit", "Cargo Audit"),
                    ("cloudsploit", "CloudSploit"),
                    ("cobalt", "Cobalt.io"),
                    ("codechecker", "CodeChecker"),
                    ("cycognito", "CyCognito"),
                    ("dockerbench", "Docker Bench Security"),
                    ("github_vulnerability", "GitHub Security Alerts"),
                    ("gitlab_container_scan", "GitLab Container Scan"),
                    ("gitleaks", "Gitleaks"),
                    ("hydra", "Hydra"),
                    ("immuniweb", "ImmuniWeb"),
                    ("netsparker", "Netsparker / Invicti"),
                    ("nexpose", "Nexpose / InsightVM"),
                    ("nuclei", "Nuclei"),
                    ("qualys", "Qualys Infrastructure"),
                    ("qualys_webapp", "Qualys Web App Scanner"),
                    ("redhatsatellite", "Red Hat Satellite"),
                    ("sonarqube", "SonarQube"),
                    ("ssh_audit", "ssh-audit"),
                    ("sslscan", "SSLScan"),
                    ("sysdig", "Sysdig"),
                    ("trivy", "Trivy"),
                    ("wapiti", "Wapiti"),
                    ("wfuzz", "Wfuzz"),
                    ("wpscan", "WPScan"),
                    ("pentest_pipeline", "Pentest Pipeline Report (MD)"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
