# Generated by Django 5.0.4 on 2026-03-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('xml', 'XML')], default='pdf', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/exports/')),
                ('error_message', models.TextField(blank=True)),
                ('options', models.JSONField(default=dict, help_text='Serialized report options (filters, template, etc.) used for this export.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='projects.subproject')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
